# Generated by Django 4.0.6 on 2022-08-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emenu',
            old_name='user',
            new_name='shop',
        ),
        migrations.AlterField(
            model_name='shop',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/shop_avatar'),
        ),
        migrations.CreateModel(
            name='Accesory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/emenu_accessory')),
                ('emenu', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.emenu')),
            ],
        ),
    ]
