# Generated by Django 4.0.6 on 2022-08-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_user_emenu_shop_alter_shop_avatar_accesory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
