# Generated by Django 4.1 on 2022-08-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_shop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emenu',
            name='shop',
        ),
        migrations.AlterField(
            model_name='shop',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Accesory',
        ),
        migrations.DeleteModel(
            name='Emenu',
        ),
    ]
