# Generated by Django 4.0.6 on 2022-08-27 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_emenu_accesory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesory',
            name='emenu',
        ),
        migrations.AddField(
            model_name='accesory',
            name='Shop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.shop'),
        ),
        migrations.DeleteModel(
            name='Emenu',
        ),
    ]
