# Generated by Django 4.0.6 on 2022-08-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_remove_accesory_emenu_accesory_shop_delete_emenu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesory',
            old_name='Shop',
            new_name='shop',
        ),
    ]
