# Generated by Django 4.0.6 on 2022-08-27 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_rename_shop_accesory_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('accesory', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.accesory')),
            ],
        ),
    ]
