# Generated by Django 4.0.6 on 2022-08-28 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_alter_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='accesory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesory', to='Home.accesory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='num',
            field=models.IntegerField(default='31508'),
        ),
    ]
