# Generated by Django 4.0.6 on 2022-08-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_alter_order_accesory_alter_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='num',
            field=models.IntegerField(default='82064'),
        ),
    ]
