# Generated by Django 4.0.6 on 2022-08-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_alter_order_date_alter_order_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Working', 'Working'), ('Done', 'Done')], default='Waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='num',
            field=models.IntegerField(default='67233'),
        ),
    ]
