# Generated by Django 4.0.6 on 2022-08-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_alter_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesory',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.shop'),
        ),
        migrations.AlterField(
            model_name='order',
            name='num',
            field=models.IntegerField(default='29465'),
        ),
    ]
