# Generated by Django 4.0.6 on 2022-08-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0006_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='usertype',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Shop owner', 'Shop owner')], default='Customer', max_length=20),
        ),
    ]
